project_id = "kqsxscjtlipregkrmucg"

[functions.generate-category-image]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
